// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsProject.Server.Models;

#nullable disable

namespace NewsProject.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230915191427_bak")]
    partial class bak
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NewsProject.Shared.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f6bb5b66-6398-47e2-b8ea-c253ccf79a7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb4aef7c-908a-4f87-b648-2df4c40b2f09",
                            Country = "Yemen",
                            Email = "bakel@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEAaowgzOkmmNXOX06rTW73waTEU1BPwc4B0fBVNCCw3vbo9dpF2aQ9E5QZBSK4nN1g==",
                            PhoneNumber = "771966828",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25b3f23c-fc9e-4fd5-ac99-62a19bf831e8",
                            TwoFactorEnabled = false,
                            UserName = "bakel"
                        });
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Barench", b =>
                {
                    b.Property<int>("BarenchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarenchID"), 1L, 1);

                    b.Property<string>("Adderess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarenchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStata")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarenchID");

                    b.ToTable("Barenches");

                    b.HasData(
                        new
                        {
                            BarenchID = 1,
                            BarenchName = "فرع تعز",
                            CurrentStata = 1
                        },
                        new
                        {
                            BarenchID = 2,
                            BarenchName = "فرع صنعاء ",
                            CurrentStata = 1
                        });
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "الالمواد الغذائية"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "المستلزمات"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "الكمبيوتر"
                        });
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"), 1L, 1);

                    b.Property<int>("BarenchID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStata")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discont")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Discontafter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qountte")
                        .HasColumnType("int");

                    b.Property<int>("SuppId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotaEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BarenchID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Invoicelist", b =>
                {
                    b.Property<int>("InvoicelistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoicelistID"), 1L, 1);

                    b.Property<int>("BarenchID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStata")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvID")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quntity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoicelistID");

                    b.HasIndex("BarenchID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductID");

                    b.ToTable("Invoicelists");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.InvoiceTemp", b =>
                {
                    b.Property<int>("InvoiceTempID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceTempID"), 1L, 1);

                    b.Property<int>("BarenchID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStata")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quntity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceTempID");

                    b.HasIndex("BarenchID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductID");

                    b.ToTable("InvoiceTemps");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<int>("BarenchID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStata")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quntity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("BarenchID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            BarenchID = 1,
                            CategoryId = 1,
                            CreatDate = new DateTime(2023, 9, 15, 22, 14, 23, 893, DateTimeKind.Local).AddTicks(6666),
                            CurrentStata = 1,
                            Price = 200m,
                            ProductName = " حليب",
                            Quntity = 20
                        },
                        new
                        {
                            ProductID = 2,
                            BarenchID = 1,
                            CategoryId = 2,
                            CreatDate = new DateTime(2023, 9, 15, 22, 14, 23, 893, DateTimeKind.Local).AddTicks(6695),
                            CurrentStata = 1,
                            Price = 4300m,
                            ProductName = " اسسوارات  ",
                            Quntity = 30
                        },
                        new
                        {
                            ProductID = 3,
                            BarenchID = 2,
                            CategoryId = 3,
                            CreatDate = new DateTime(2023, 9, 15, 22, 14, 23, 893, DateTimeKind.Local).AddTicks(6712),
                            CurrentStata = 1,
                            Price = 1600m,
                            ProductName = " كمبيوتر ",
                            Quntity = 200
                        },
                        new
                        {
                            ProductID = 4,
                            BarenchID = 1,
                            CategoryId = 1,
                            CreatDate = new DateTime(2023, 9, 15, 22, 14, 23, 893, DateTimeKind.Local).AddTicks(6721),
                            CurrentStata = 1,
                            Price = 20m,
                            ProductName = " دقيق",
                            Quntity = 30
                        });
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"), 1L, 1);

                    b.Property<string>("Addrees")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BarenchID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStata")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.HasIndex("BarenchID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            Addrees = "Taiz",
                            BarenchID = 1,
                            CreatDate = new DateTime(2023, 9, 15, 22, 14, 23, 893, DateTimeKind.Local).AddTicks(6740),
                            CurrentStata = 1,
                            Emil = "bakel@gmail.com",
                            Phon = "771966828",
                            SupplierName = "Bakel Asharabe"
                        },
                        new
                        {
                            SupplierID = 2,
                            Addrees = "Taiz",
                            BarenchID = 1,
                            CreatDate = new DateTime(2023, 9, 15, 22, 14, 23, 893, DateTimeKind.Local).AddTicks(6752),
                            CurrentStata = 1,
                            Emil = "mog@gmail.com",
                            Phon = "771966828",
                            SupplierName = "Mohmmed Asharabe"
                        },
                        new
                        {
                            SupplierID = 3,
                            Addrees = "Taiz",
                            BarenchID = 1,
                            CreatDate = new DateTime(2023, 9, 15, 22, 14, 23, 893, DateTimeKind.Local).AddTicks(6761),
                            CurrentStata = 1,
                            Emil = "bak@eail.com",
                            Phon = "771966828",
                            SupplierName = " Asharabe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsProject.Shared.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Invoice", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.Barench", "Barench")
                        .WithMany()
                        .HasForeignKey("BarenchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsProject.Shared.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID");

                    b.Navigation("Barench");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Invoicelist", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.Barench", "Barench")
                        .WithMany()
                        .HasForeignKey("BarenchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsProject.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsProject.Shared.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItemlist")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("NewsProject.Shared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barench");

                    b.Navigation("Category");

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.InvoiceTemp", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.Barench", "Barench")
                        .WithMany()
                        .HasForeignKey("BarenchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsProject.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsProject.Shared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barench");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Product", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.Barench", "Barench")
                        .WithMany()
                        .HasForeignKey("BarenchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsProject.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barench");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Supplier", b =>
                {
                    b.HasOne("NewsProject.Shared.Models.Barench", "Barench")
                        .WithMany()
                        .HasForeignKey("BarenchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barench");
                });

            modelBuilder.Entity("NewsProject.Shared.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItemlist");
                });
#pragma warning restore 612, 618
        }
    }
}
